my:
  sun:
    id: 101
    name: proitine
    price: 1000.595841659164161651
    list:
    - kasrawad
    - kamal patidar
    - ram mandir chak
    set:
    - 1242
    - 155
    - 5455
    map:
      data: 123626
      person: prasun  
    packet-info:
      id: 10282
      name: prasun patidar
       
    
    
    
 